### ISSUE TITLE
Have the choice between an incremental mode or a big bang mode

### ISSUE THREAD

**Issue by fdelbrayelle** [fdelbrayelle/generator-jhipster-kafka#53]
##### **Overview of the feature request**

Give the choice to the use between:
- an incremental mode: keep the old configuration and add only new things
- a big bang mode: erasing all the configuration and generated files before to generate a new configuration with new generated files

##### **Motivation for or Use Case**

The actual prompt system does not allow to choose between management alternatives. The module needs to be more flexible to match more use cases.

This feature request won't implement the modification or removal of individual existing configuration.

##### **Related issues or PR**

Closes deprecated issues #48 and #52

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by monxxi** [comment]
in this feature, i suggest these behaviours:
- "BigBang" Mode : 
>  - be able to regenerate all application kafka configurations
>  - disable spring bean instanciation of already existing producer/consumer to avoid errors at startup  or may be delete them (but some specifics code could be lost )
- "Incremental" Mode :
>  - only be able to append/create kafka consumer/producer only for entity where the implementation is missing
>  - in this case, it may be interesting to use a loop to ask for each entity  wished, the implementation wish.
>> for example:
>>>   - For which entity do you want to generate consumer and/or producer? (provide only entities without consumer or producer)
>>>    - Which Kafka components would you like to generate for the entity <placeholder>? (provide only missing components)

**Comment by fdelbrayelle** [comment]
For the **big bang mode** I'd delete all generated code including consumers and producers rather than just disable them. As a user if you are choosing big bang mode you are supposed to master what you do. Maybe we could put an alert in red in the prompt to warn the user?

Concerning the **incremental mode**, I agree but if an entity already have both a consumer and a producer it shouldn't be listed. What do you think about that?

**Comment by monxxi** [comment]
i'm agree, i'll work towards
