### ISSUE TITLE
Generate consumers/producers with no Entity linked

### ISSUE THREAD

**Issue by fdelbrayelle** [fdelbrayelle/generator-jhipster-kafka#57]
##### **Overview of the feature request**

Give the choice to generate consumers and producers without linking a generated entity.

##### **Motivation for or Use Case**

Currently, the user has to choose an entity to generate consumers and producers. In real life this is not mandatory.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by fdelbrayelle** [comment]
@pascalgrimaud What behaviour would you expect if selecting no entity?

I mean currently there is an associated type with generated consumers and producers. Would it be String for the moment? By default? Or anything else?

**Comment by pascalgrimaud** [comment]
There can be different behaviour:
- prompt without nothing, except configuration : generate config, Generic, akhq
- prompt with Consumer or Producer, not linked to an existing entity
- prompt with Consumer or Producer linked to entity

**Comment by fdelbrayelle** [comment]
Ok, but in the case of consumers/producers not linked to an existing entity to which type should it be associated? String? Like this: `public class MyNotLinkedConsumer extends GenericConsumer<String>`?

**Comment by pascalgrimaud** [comment]
It can simply be String. No need to ask, as it will be customized with business logic inside
