### ISSUE TITLE
CI: skip-prompts

### ISSUE THREAD

**Issue by pascalgrimaud** [fdelbrayelle/generator-jhipster-kafka#59]
In the CI, there is the use of `yo jhipster-kafka --force --skip-prompts`
This command should not generate this:

```
➜ l src/main/java/io/github/pascalgrimaud/burger/service/kafka/consumer 
total 12K
drwxr-xr-x 2 pgrimaud pgrimaud 4,0K mai   26 12:34 .
drwxr-xr-x 6 pgrimaud pgrimaud 4,0K mai   26 12:34 ..
-rw-r--r-- 1 pgrimaud pgrimaud 1,5K mai   26 12:34 DocumentBankAccountConsumer.java
```

This file is not related at all to the project, as the command is used for:
--force: to replace all files
--skip-prompts: to use default option in prompt

Linked to https://github.com/fdelbrayelle/generator-jhipster-kafka/issues/57

**Comment by fdelbrayelle** [comment]
Why should it be linked with #57 ?
If the prompts are skipped, today as consumers/producers are linked to an entity it should have another behaviour.

**Comment by pascalgrimaud** [comment]
Linked to #57 because in #57, we should be allowed to use "default" answer. Default answer = without entities selected or a new project without entities yet

**Comment by fdelbrayelle** [comment]
Ok so maybe both issues could be realize simultaneously in this case.

**Comment by pascalgrimaud** [comment]
yes it could be, feel free to close this one if you want

**Comment by fdelbrayelle** [comment]
I prefer to keep this opened as the `--skip-prompts` could be refactored to be clearer.
